os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker
env:
- PROJECT=sql
- PROJECT=wrappedresponse

script:
  - scripts/init_tests.sh
  - cd rapydo_tests
  - APP_MODE=test rapydo --project ${PROJECT} init
  - rapydo -s frontend pull
  - rapydo dump
  - docker-compose up --exit-code-from frontend frontend

  - docker-compose down
  - cp data/${PROJECT}/karma/lcov.info . 
  - bash <(curl -s https://codecov.io/bash) -R submodules/frontend

  - rapydo --prod --project ${PROJECT} init
  # Cleanup before testing in production mode
  - rm -rf data/${PROJECT}/frontend/package-lock.json data/${PROJECT}/frontend/node_modules
  - rapydo -s frontend start
  - rapydo -s frontend logs --follow
  - docker-compose logs --tail 1 frontend 2>&1 | grep "files have been compressed."
