os: linux
dist: bionic
language: python
python:
- 3.8
services:
- docker
env:
- PROJECT=sql
- PROJECT=wrappedresponse
# cache:
#   directories:
#    - /home/travis/rapydo_tests/data/$PROJECT/frontend

script:
  - CURRENT_VERSION=$(grep '"version"' src/package.json | awk {'print $2'} | tr -d '", ')
  - BRANCH=$([  -z "$TRAVIS_PULL_REQUEST_BRANCH" ] && echo "$TRAVIS_BRANCH" || echo "$TRAVIS_PULL_REQUEST_BRANCH")
  - pip3 install --upgrade git+https://github.com/rapydo/do.git@${CURRENT_VERSION}
  - git clone -b ${BRANCH} --depth=1 https://github.com/rapydo/tests.git rapydo_tests
  - cd rapydo_tests
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then git pull origin $TRAVIS_BRANCH; fi
  - APP_MODE=test rapydo --project ${PROJECT} init
  - rapydo -s frontend pull
  - rapydo dump
  - docker-compose up --exit-code-from frontend frontend

  - docker-compose down
  - cp data/${PROJECT}/karma/lcov.info . 
  - bash <(curl -s https://codecov.io/bash) -R submodules/frontend

  - rapydo --prod --project ${PROJECT} init --force
  # Cleanup before testing in production mode
  - rm -rf data/${PROJECT}/frontend/package-lock.json data/${PROJECT}/frontend/node_modules
  - rapydo -s frontend start
  - rapydo -s frontend logs --follow
  - docker-compose logs --tail 2 frontend 2>&1 | grep "files have been compressed."
